name: Ballerina Distribution Build 

on:
  push:
    branches:
      - master
      - stage
      - ballerina-1.1.x
  pull_request:
    branches:
      - master
      - stage
      - ballerina-1.1.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Ballerina Distribution
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build --stacktrace --scan --console=plain --no-daemon
